// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Account
type Account struct {
	ID          uuid.UUID      `json:"id"`
	Provider    string         `json:"provider"`
	Reliability Reliability    `json:"reliability"`
	DisplayName string         `json:"displayName"`
	Status      AccountStatus  `json:"status"`
	LastSyncAt  OptNilDateTime `json:"lastSyncAt"`
	// Empty when healthy. Never contains credentials.
	LastError OptString `json:"lastError"`
}

// GetID returns the value of ID.
func (s *Account) GetID() uuid.UUID {
	return s.ID
}

// GetProvider returns the value of Provider.
func (s *Account) GetProvider() string {
	return s.Provider
}

// GetReliability returns the value of Reliability.
func (s *Account) GetReliability() Reliability {
	return s.Reliability
}

// GetDisplayName returns the value of DisplayName.
func (s *Account) GetDisplayName() string {
	return s.DisplayName
}

// GetStatus returns the value of Status.
func (s *Account) GetStatus() AccountStatus {
	return s.Status
}

// GetLastSyncAt returns the value of LastSyncAt.
func (s *Account) GetLastSyncAt() OptNilDateTime {
	return s.LastSyncAt
}

// GetLastError returns the value of LastError.
func (s *Account) GetLastError() OptString {
	return s.LastError
}

// SetID sets the value of ID.
func (s *Account) SetID(val uuid.UUID) {
	s.ID = val
}

// SetProvider sets the value of Provider.
func (s *Account) SetProvider(val string) {
	s.Provider = val
}

// SetReliability sets the value of Reliability.
func (s *Account) SetReliability(val Reliability) {
	s.Reliability = val
}

// SetDisplayName sets the value of DisplayName.
func (s *Account) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetStatus sets the value of Status.
func (s *Account) SetStatus(val AccountStatus) {
	s.Status = val
}

// SetLastSyncAt sets the value of LastSyncAt.
func (s *Account) SetLastSyncAt(val OptNilDateTime) {
	s.LastSyncAt = val
}

// SetLastError sets the value of LastError.
func (s *Account) SetLastError(val OptString) {
	s.LastError = val
}

// Ref: #/components/schemas/AccountList
type AccountList struct {
	Items []Account `json:"items"`
}

// GetItems returns the value of Items.
func (s *AccountList) GetItems() []Account {
	return s.Items
}

// SetItems sets the value of Items.
func (s *AccountList) SetItems(val []Account) {
	s.Items = val
}

// The account's health right now, as distinct from its reliability tier.
// Ref: #/components/schemas/AccountStatus
type AccountStatus string

const (
	AccountStatusConnected    AccountStatus = "connected"
	AccountStatusError        AccountStatus = "error"
	AccountStatusDisconnected AccountStatus = "disconnected"
)

// AllValues returns all AccountStatus values.
func (AccountStatus) AllValues() []AccountStatus {
	return []AccountStatus{
		AccountStatusConnected,
		AccountStatusError,
		AccountStatusDisconnected,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AccountStatus) MarshalText() ([]byte, error) {
	switch s {
	case AccountStatusConnected:
		return []byte(s), nil
	case AccountStatusError:
		return []byte(s), nil
	case AccountStatusDisconnected:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AccountStatus) UnmarshalText(data []byte) error {
	switch AccountStatus(data) {
	case AccountStatusConnected:
		*s = AccountStatusConnected
		return nil
	case AccountStatusError:
		*s = AccountStatusError
		return nil
	case AccountStatusDisconnected:
		*s = AccountStatusDisconnected
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// What decided this signal's placement, so a misfiling can be traced.
// Ref: #/components/schemas/AssignedBy
type AssignedBy string

const (
	AssignedByRule   AssignedBy = "rule"
	AssignedByModel  AssignedBy = "model"
	AssignedByManual AssignedBy = "manual"
)

// AllValues returns all AssignedBy values.
func (AssignedBy) AllValues() []AssignedBy {
	return []AssignedBy{
		AssignedByRule,
		AssignedByModel,
		AssignedByManual,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AssignedBy) MarshalText() ([]byte, error) {
	switch s {
	case AssignedByRule:
		return []byte(s), nil
	case AssignedByModel:
		return []byte(s), nil
	case AssignedByManual:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AssignedBy) UnmarshalText(data []byte) error {
	switch AssignedBy(data) {
	case AssignedByRule:
		*s = AssignedByRule
		return nil
	case AssignedByModel:
		*s = AssignedByModel
		return nil
	case AssignedByManual:
		*s = AssignedByManual
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// How a sign-in method authenticates. `zalo` and `facebook` are sign-in products distinct from their
// messaging APIs — linking one grants no access to messages.
// Ref: #/components/schemas/AuthProviderKind
type AuthProviderKind string

const (
	AuthProviderKindGoogle   AuthProviderKind = "google"
	AuthProviderKindZalo     AuthProviderKind = "zalo"
	AuthProviderKindFacebook AuthProviderKind = "facebook"
	AuthProviderKindPasskey  AuthProviderKind = "passkey"
	AuthProviderKindPassword AuthProviderKind = "password"
)

// AllValues returns all AuthProviderKind values.
func (AuthProviderKind) AllValues() []AuthProviderKind {
	return []AuthProviderKind{
		AuthProviderKindGoogle,
		AuthProviderKindZalo,
		AuthProviderKindFacebook,
		AuthProviderKindPasskey,
		AuthProviderKindPassword,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AuthProviderKind) MarshalText() ([]byte, error) {
	switch s {
	case AuthProviderKindGoogle:
		return []byte(s), nil
	case AuthProviderKindZalo:
		return []byte(s), nil
	case AuthProviderKindFacebook:
		return []byte(s), nil
	case AuthProviderKindPasskey:
		return []byte(s), nil
	case AuthProviderKindPassword:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AuthProviderKind) UnmarshalText(data []byte) error {
	switch AuthProviderKind(data) {
	case AuthProviderKindGoogle:
		*s = AuthProviderKindGoogle
		return nil
	case AuthProviderKindZalo:
		*s = AuthProviderKindZalo
		return nil
	case AuthProviderKindFacebook:
		*s = AuthProviderKindFacebook
		return nil
	case AuthProviderKindPasskey:
		*s = AuthProviderKindPasskey
		return nil
	case AuthProviderKindPassword:
		*s = AuthProviderKindPassword
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// CompleteGoogleSignInFound is response for CompleteGoogleSignIn operation.
type CompleteGoogleSignInFound struct {
	Location  string
	SetCookie OptString
}

// GetLocation returns the value of Location.
func (s *CompleteGoogleSignInFound) GetLocation() string {
	return s.Location
}

// GetSetCookie returns the value of SetCookie.
func (s *CompleteGoogleSignInFound) GetSetCookie() OptString {
	return s.SetCookie
}

// SetLocation sets the value of Location.
func (s *CompleteGoogleSignInFound) SetLocation(val string) {
	s.Location = val
}

// SetSetCookie sets the value of SetCookie.
func (s *CompleteGoogleSignInFound) SetSetCookie(val OptString) {
	s.SetCookie = val
}

func (*CompleteGoogleSignInFound) completeGoogleSignInRes() {}

// Ref: #/components/schemas/Context
type Context struct {
	ID uuid.UUID `json:"id"`
	// Null for a root context. A child inherits its parent's defaults.
	ParentId OptNilUUID   `json:"parentId"`
	Slug     string       `json:"slug"`
	Name     string       `json:"name"`
	Kind     ContextKind  `json:"kind"`
	Color    OptNilString `json:"color"`
	// How the system writes on the owner's behalf in this context.
	ToneProfile OptString `json:"toneProfile"`
	// Display order among siblings.
	Position   int32     `json:"position"`
	IsArchived bool      `json:"isArchived"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Context) GetID() uuid.UUID {
	return s.ID
}

// GetParentId returns the value of ParentId.
func (s *Context) GetParentId() OptNilUUID {
	return s.ParentId
}

// GetSlug returns the value of Slug.
func (s *Context) GetSlug() string {
	return s.Slug
}

// GetName returns the value of Name.
func (s *Context) GetName() string {
	return s.Name
}

// GetKind returns the value of Kind.
func (s *Context) GetKind() ContextKind {
	return s.Kind
}

// GetColor returns the value of Color.
func (s *Context) GetColor() OptNilString {
	return s.Color
}

// GetToneProfile returns the value of ToneProfile.
func (s *Context) GetToneProfile() OptString {
	return s.ToneProfile
}

// GetPosition returns the value of Position.
func (s *Context) GetPosition() int32 {
	return s.Position
}

// GetIsArchived returns the value of IsArchived.
func (s *Context) GetIsArchived() bool {
	return s.IsArchived
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Context) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Context) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Context) SetID(val uuid.UUID) {
	s.ID = val
}

// SetParentId sets the value of ParentId.
func (s *Context) SetParentId(val OptNilUUID) {
	s.ParentId = val
}

// SetSlug sets the value of Slug.
func (s *Context) SetSlug(val string) {
	s.Slug = val
}

// SetName sets the value of Name.
func (s *Context) SetName(val string) {
	s.Name = val
}

// SetKind sets the value of Kind.
func (s *Context) SetKind(val ContextKind) {
	s.Kind = val
}

// SetColor sets the value of Color.
func (s *Context) SetColor(val OptNilString) {
	s.Color = val
}

// SetToneProfile sets the value of ToneProfile.
func (s *Context) SetToneProfile(val OptString) {
	s.ToneProfile = val
}

// SetPosition sets the value of Position.
func (s *Context) SetPosition(val int32) {
	s.Position = val
}

// SetIsArchived sets the value of IsArchived.
func (s *Context) SetIsArchived(val bool) {
	s.IsArchived = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Context) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Context) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Context) getContextRes() {}

// Ref: #/components/schemas/ContextKind
type ContextKind string

const (
	ContextKindWork     ContextKind = "work"
	ContextKindStudy    ContextKind = "study"
	ContextKindPersonal ContextKind = "personal"
)

// AllValues returns all ContextKind values.
func (ContextKind) AllValues() []ContextKind {
	return []ContextKind{
		ContextKindWork,
		ContextKindStudy,
		ContextKindPersonal,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ContextKind) MarshalText() ([]byte, error) {
	switch s {
	case ContextKindWork:
		return []byte(s), nil
	case ContextKindStudy:
		return []byte(s), nil
	case ContextKindPersonal:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ContextKind) UnmarshalText(data []byte) error {
	switch ContextKind(data) {
	case ContextKindWork:
		*s = ContextKindWork
		return nil
	case ContextKindStudy:
		*s = ContextKindStudy
		return nil
	case ContextKindPersonal:
		*s = ContextKindPersonal
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ContextList
type ContextList struct {
	Items []Context `json:"items"`
}

// GetItems returns the value of Items.
func (s *ContextList) GetItems() []Context {
	return s.Items
}

// SetItems sets the value of Items.
func (s *ContextList) SetItems(val []Context) {
	s.Items = val
}

// Ref: #/components/schemas/CurrentSession
type CurrentSession struct {
	User    SignedInUser `json:"user"`
	Session Session      `json:"session"`
}

// GetUser returns the value of User.
func (s *CurrentSession) GetUser() SignedInUser {
	return s.User
}

// GetSession returns the value of Session.
func (s *CurrentSession) GetSession() Session {
	return s.Session
}

// SetUser sets the value of User.
func (s *CurrentSession) SetUser(val SignedInUser) {
	s.User = val
}

// SetSession sets the value of Session.
func (s *CurrentSession) SetSession(val Session) {
	s.Session = val
}

func (*CurrentSession) getCurrentSessionRes() {}

// CurrentSessionHeaders wraps CurrentSession with response headers.
type CurrentSessionHeaders struct {
	SetCookie OptString
	Response  CurrentSession
}

// GetSetCookie returns the value of SetCookie.
func (s *CurrentSessionHeaders) GetSetCookie() OptString {
	return s.SetCookie
}

// GetResponse returns the value of Response.
func (s *CurrentSessionHeaders) GetResponse() CurrentSession {
	return s.Response
}

// SetSetCookie sets the value of SetCookie.
func (s *CurrentSessionHeaders) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// SetResponse sets the value of Response.
func (s *CurrentSessionHeaders) SetResponse(val CurrentSession) {
	s.Response = val
}

func (*CurrentSessionHeaders) loginRes()    {}
func (*CurrentSessionHeaders) registerRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	// Stable, machine-readable. Safe to switch on.
	Code string `json:"code"`
	// Human-readable and safe to display. Never contains payload contents, credentials, or anyone's
	// correspondence.
	Message string `json:"message"`
	// Structured detail, when there is any that is safe to return.
	Details OptErrorDetails `json:"details"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *Error) GetDetails() OptErrorDetails {
	return s.Details
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *Error) SetDetails(val OptErrorDetails) {
	s.Details = val
}

// Structured detail, when there is any that is safe to return.
type ErrorDetails map[string]jx.Raw

func (s *ErrorDetails) init() ErrorDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Every error this API returns has this shape, so a client has exactly one branch to write.
// Ref: #/components/schemas/ErrorEnvelope
type ErrorEnvelope struct {
	Error Error `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorEnvelope) GetError() Error {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorEnvelope) SetError(val Error) {
	s.Error = val
}

func (*ErrorEnvelope) completeGoogleSignInRes() {}
func (*ErrorEnvelope) getContextRes()           {}
func (*ErrorEnvelope) getCurrentSessionRes()    {}
func (*ErrorEnvelope) listAuthProvidersRes()    {}
func (*ErrorEnvelope) listSessionsRes()         {}
func (*ErrorEnvelope) loginRes()                {}
func (*ErrorEnvelope) registerRes()             {}
func (*ErrorEnvelope) signOutRes()              {}

// ErrorEnvelopeHeaders wraps ErrorEnvelope with response headers.
type ErrorEnvelopeHeaders struct {
	RetryAfter OptInt
	Response   ErrorEnvelope
}

// GetRetryAfter returns the value of RetryAfter.
func (s *ErrorEnvelopeHeaders) GetRetryAfter() OptInt {
	return s.RetryAfter
}

// GetResponse returns the value of Response.
func (s *ErrorEnvelopeHeaders) GetResponse() ErrorEnvelope {
	return s.Response
}

// SetRetryAfter sets the value of RetryAfter.
func (s *ErrorEnvelopeHeaders) SetRetryAfter(val OptInt) {
	s.RetryAfter = val
}

// SetResponse sets the value of Response.
func (s *ErrorEnvelopeHeaders) SetResponse(val ErrorEnvelope) {
	s.Response = val
}

func (*ErrorEnvelopeHeaders) loginRes() {}

// ErrorStatusCode wraps ErrorEnvelope with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   ErrorEnvelope
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() ErrorEnvelope {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val ErrorEnvelope) {
	s.Response = val
}

// Ref: #/components/schemas/LinkedProvider
type LinkedProvider struct {
	ID   uuid.UUID        `json:"id"`
	Kind AuthProviderKind `json:"kind"`
	// What the provider reported when this was linked. Display only — it is not what authenticates, and
	// a passkey has none.
	Email       OptString      `json:"email"`
	IsPrimary   bool           `json:"isPrimary"`
	LinkedAt    time.Time      `json:"linkedAt"`
	LastLoginAt OptNilDateTime `json:"lastLoginAt"`
}

// GetID returns the value of ID.
func (s *LinkedProvider) GetID() uuid.UUID {
	return s.ID
}

// GetKind returns the value of Kind.
func (s *LinkedProvider) GetKind() AuthProviderKind {
	return s.Kind
}

// GetEmail returns the value of Email.
func (s *LinkedProvider) GetEmail() OptString {
	return s.Email
}

// GetIsPrimary returns the value of IsPrimary.
func (s *LinkedProvider) GetIsPrimary() bool {
	return s.IsPrimary
}

// GetLinkedAt returns the value of LinkedAt.
func (s *LinkedProvider) GetLinkedAt() time.Time {
	return s.LinkedAt
}

// GetLastLoginAt returns the value of LastLoginAt.
func (s *LinkedProvider) GetLastLoginAt() OptNilDateTime {
	return s.LastLoginAt
}

// SetID sets the value of ID.
func (s *LinkedProvider) SetID(val uuid.UUID) {
	s.ID = val
}

// SetKind sets the value of Kind.
func (s *LinkedProvider) SetKind(val AuthProviderKind) {
	s.Kind = val
}

// SetEmail sets the value of Email.
func (s *LinkedProvider) SetEmail(val OptString) {
	s.Email = val
}

// SetIsPrimary sets the value of IsPrimary.
func (s *LinkedProvider) SetIsPrimary(val bool) {
	s.IsPrimary = val
}

// SetLinkedAt sets the value of LinkedAt.
func (s *LinkedProvider) SetLinkedAt(val time.Time) {
	s.LinkedAt = val
}

// SetLastLoginAt sets the value of LastLoginAt.
func (s *LinkedProvider) SetLastLoginAt(val OptNilDateTime) {
	s.LastLoginAt = val
}

// Ref: #/components/schemas/LinkedProviderList
type LinkedProviderList struct {
	Items []LinkedProvider `json:"items"`
}

// GetItems returns the value of Items.
func (s *LinkedProviderList) GetItems() []LinkedProvider {
	return s.Items
}

// SetItems sets the value of Items.
func (s *LinkedProviderList) SetItems(val []LinkedProvider) {
	s.Items = val
}

func (*LinkedProviderList) listAuthProvidersRes() {}

// Ref: #/components/schemas/LoginRequest
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *LoginRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *LoginRequest) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *LoginRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *LoginRequest) SetPassword(val string) {
	s.Password = val
}

// NewOptAssignedBy returns new OptAssignedBy with value set to v.
func NewOptAssignedBy(v AssignedBy) OptAssignedBy {
	return OptAssignedBy{
		Value: v,
		Set:   true,
	}
}

// OptAssignedBy is optional AssignedBy.
type OptAssignedBy struct {
	Value AssignedBy
	Set   bool
}

// IsSet returns true if OptAssignedBy was set.
func (o OptAssignedBy) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAssignedBy) Reset() {
	var v AssignedBy
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAssignedBy) SetTo(v AssignedBy) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAssignedBy) Get() (v AssignedBy, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAssignedBy) Or(d AssignedBy) AssignedBy {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAuthProviderKind returns new OptAuthProviderKind with value set to v.
func NewOptAuthProviderKind(v AuthProviderKind) OptAuthProviderKind {
	return OptAuthProviderKind{
		Value: v,
		Set:   true,
	}
}

// OptAuthProviderKind is optional AuthProviderKind.
type OptAuthProviderKind struct {
	Value AuthProviderKind
	Set   bool
}

// IsSet returns true if OptAuthProviderKind was set.
func (o OptAuthProviderKind) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAuthProviderKind) Reset() {
	var v AuthProviderKind
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAuthProviderKind) SetTo(v AuthProviderKind) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAuthProviderKind) Get() (v AuthProviderKind, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAuthProviderKind) Or(d AuthProviderKind) AuthProviderKind {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptErrorDetails returns new OptErrorDetails with value set to v.
func NewOptErrorDetails(v ErrorDetails) OptErrorDetails {
	return OptErrorDetails{
		Value: v,
		Set:   true,
	}
}

// OptErrorDetails is optional ErrorDetails.
type OptErrorDetails struct {
	Value ErrorDetails
	Set   bool
}

// IsSet returns true if OptErrorDetails was set.
func (o OptErrorDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorDetails) Reset() {
	var v ErrorDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorDetails) SetTo(v ErrorDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorDetails) Get() (v ErrorDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorDetails) Or(d ErrorDetails) ErrorDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilDateTime) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilUUID) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/RegisterRequest
type RegisterRequest struct {
	Email string `json:"email"`
	// Length is the only rule the contract enforces. Composition rules push people towards predictable
	// substitutions; length does not.
	Password    string `json:"password"`
	DisplayName string `json:"displayName"`
}

// GetEmail returns the value of Email.
func (s *RegisterRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *RegisterRequest) GetPassword() string {
	return s.Password
}

// GetDisplayName returns the value of DisplayName.
func (s *RegisterRequest) GetDisplayName() string {
	return s.DisplayName
}

// SetEmail sets the value of Email.
func (s *RegisterRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *RegisterRequest) SetPassword(val string) {
	s.Password = val
}

// SetDisplayName sets the value of DisplayName.
func (s *RegisterRequest) SetDisplayName(val string) {
	s.DisplayName = val
}

// How complete this source can be assumed to be. Only `official` may be presented as the whole
// picture.
// Ref: #/components/schemas/Reliability
type Reliability string

const (
	ReliabilityOfficial   Reliability = "official"
	ReliabilityUnofficial Reliability = "unofficial"
	ReliabilityManual     Reliability = "manual"
)

// AllValues returns all Reliability values.
func (Reliability) AllValues() []Reliability {
	return []Reliability{
		ReliabilityOfficial,
		ReliabilityUnofficial,
		ReliabilityManual,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Reliability) MarshalText() ([]byte, error) {
	switch s {
	case ReliabilityOfficial:
		return []byte(s), nil
	case ReliabilityUnofficial:
		return []byte(s), nil
	case ReliabilityManual:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Reliability) UnmarshalText(data []byte) error {
	switch Reliability(data) {
	case ReliabilityOfficial:
		*s = ReliabilityOfficial
		return nil
	case ReliabilityUnofficial:
		*s = ReliabilityUnofficial
		return nil
	case ReliabilityManual:
		*s = ReliabilityManual
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// RevokeSessionNoContent is response for RevokeSession operation.
type RevokeSessionNoContent struct{}

func (*RevokeSessionNoContent) revokeSessionRes() {}

type RevokeSessionNotFound ErrorEnvelope

func (*RevokeSessionNotFound) revokeSessionRes() {}

type RevokeSessionUnauthorized ErrorEnvelope

func (*RevokeSessionUnauthorized) revokeSessionRes() {}

// A browser that is signed in. The token itself never appears here — only the server-side record of
// it.
// Ref: #/components/schemas/Session
type Session struct {
	ID           uuid.UUID           `json:"id"`
	ProviderKind OptAuthProviderKind `json:"providerKind"`
	IssuedAt     time.Time           `json:"issuedAt"`
	LastSeenAt   time.Time           `json:"lastSeenAt"`
	ExpiresAt    time.Time           `json:"expiresAt"`
	// Enough to recognise which browser this is, and revoke the right one.
	UserAgent OptString    `json:"userAgent"`
	IP        OptNilString `json:"ip"`
	// True for the session making this request.
	IsCurrent bool `json:"isCurrent"`
}

// GetID returns the value of ID.
func (s *Session) GetID() uuid.UUID {
	return s.ID
}

// GetProviderKind returns the value of ProviderKind.
func (s *Session) GetProviderKind() OptAuthProviderKind {
	return s.ProviderKind
}

// GetIssuedAt returns the value of IssuedAt.
func (s *Session) GetIssuedAt() time.Time {
	return s.IssuedAt
}

// GetLastSeenAt returns the value of LastSeenAt.
func (s *Session) GetLastSeenAt() time.Time {
	return s.LastSeenAt
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *Session) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// GetUserAgent returns the value of UserAgent.
func (s *Session) GetUserAgent() OptString {
	return s.UserAgent
}

// GetIP returns the value of IP.
func (s *Session) GetIP() OptNilString {
	return s.IP
}

// GetIsCurrent returns the value of IsCurrent.
func (s *Session) GetIsCurrent() bool {
	return s.IsCurrent
}

// SetID sets the value of ID.
func (s *Session) SetID(val uuid.UUID) {
	s.ID = val
}

// SetProviderKind sets the value of ProviderKind.
func (s *Session) SetProviderKind(val OptAuthProviderKind) {
	s.ProviderKind = val
}

// SetIssuedAt sets the value of IssuedAt.
func (s *Session) SetIssuedAt(val time.Time) {
	s.IssuedAt = val
}

// SetLastSeenAt sets the value of LastSeenAt.
func (s *Session) SetLastSeenAt(val time.Time) {
	s.LastSeenAt = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *Session) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}

// SetUserAgent sets the value of UserAgent.
func (s *Session) SetUserAgent(val OptString) {
	s.UserAgent = val
}

// SetIP sets the value of IP.
func (s *Session) SetIP(val OptNilString) {
	s.IP = val
}

// SetIsCurrent sets the value of IsCurrent.
func (s *Session) SetIsCurrent(val bool) {
	s.IsCurrent = val
}

type SessionCookie struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *SessionCookie) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *SessionCookie) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *SessionCookie) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *SessionCookie) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/SessionList
type SessionList struct {
	Items []Session `json:"items"`
}

// GetItems returns the value of Items.
func (s *SessionList) GetItems() []Session {
	return s.Items
}

// SetItems sets the value of Items.
func (s *SessionList) SetItems(val []Session) {
	s.Items = val
}

func (*SessionList) listSessionsRes() {}

// SignOutNoContent is response for SignOut operation.
type SignOutNoContent struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *SignOutNoContent) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *SignOutNoContent) SetSetCookie(val OptString) {
	s.SetCookie = val
}

func (*SignOutNoContent) signOutRes() {}

// A signal as the timeline shows it. `payload` is deliberately absent: the raw item stays in the
// database.
// Ref: #/components/schemas/Signal
type Signal struct {
	ID        uuid.UUID  `json:"id"`
	AccountId uuid.UUID  `json:"accountId"`
	Kind      SignalKind `json:"kind"`
	Subject   OptString  `json:"subject"`
	// A short excerpt, enough to recognise the item in a list.
	Snippet OptString `json:"snippet"`
	// When the item actually happened, not when it was fetched.
	OccurredAt time.Time `json:"occurredAt"`
	IngestedAt time.Time `json:"ingestedAt"`
	// Whether extraction has already run over this signal.
	Processed bool `json:"processed"`
	// The context this row was returned under.
	ContextId OptUUID `json:"contextId"`
	// How certain the placement is. Always 1 for a rule match.
	Confidence OptFloat64    `json:"confidence"`
	AssignedBy OptAssignedBy `json:"assignedBy"`
}

// GetID returns the value of ID.
func (s *Signal) GetID() uuid.UUID {
	return s.ID
}

// GetAccountId returns the value of AccountId.
func (s *Signal) GetAccountId() uuid.UUID {
	return s.AccountId
}

// GetKind returns the value of Kind.
func (s *Signal) GetKind() SignalKind {
	return s.Kind
}

// GetSubject returns the value of Subject.
func (s *Signal) GetSubject() OptString {
	return s.Subject
}

// GetSnippet returns the value of Snippet.
func (s *Signal) GetSnippet() OptString {
	return s.Snippet
}

// GetOccurredAt returns the value of OccurredAt.
func (s *Signal) GetOccurredAt() time.Time {
	return s.OccurredAt
}

// GetIngestedAt returns the value of IngestedAt.
func (s *Signal) GetIngestedAt() time.Time {
	return s.IngestedAt
}

// GetProcessed returns the value of Processed.
func (s *Signal) GetProcessed() bool {
	return s.Processed
}

// GetContextId returns the value of ContextId.
func (s *Signal) GetContextId() OptUUID {
	return s.ContextId
}

// GetConfidence returns the value of Confidence.
func (s *Signal) GetConfidence() OptFloat64 {
	return s.Confidence
}

// GetAssignedBy returns the value of AssignedBy.
func (s *Signal) GetAssignedBy() OptAssignedBy {
	return s.AssignedBy
}

// SetID sets the value of ID.
func (s *Signal) SetID(val uuid.UUID) {
	s.ID = val
}

// SetAccountId sets the value of AccountId.
func (s *Signal) SetAccountId(val uuid.UUID) {
	s.AccountId = val
}

// SetKind sets the value of Kind.
func (s *Signal) SetKind(val SignalKind) {
	s.Kind = val
}

// SetSubject sets the value of Subject.
func (s *Signal) SetSubject(val OptString) {
	s.Subject = val
}

// SetSnippet sets the value of Snippet.
func (s *Signal) SetSnippet(val OptString) {
	s.Snippet = val
}

// SetOccurredAt sets the value of OccurredAt.
func (s *Signal) SetOccurredAt(val time.Time) {
	s.OccurredAt = val
}

// SetIngestedAt sets the value of IngestedAt.
func (s *Signal) SetIngestedAt(val time.Time) {
	s.IngestedAt = val
}

// SetProcessed sets the value of Processed.
func (s *Signal) SetProcessed(val bool) {
	s.Processed = val
}

// SetContextId sets the value of ContextId.
func (s *Signal) SetContextId(val OptUUID) {
	s.ContextId = val
}

// SetConfidence sets the value of Confidence.
func (s *Signal) SetConfidence(val OptFloat64) {
	s.Confidence = val
}

// SetAssignedBy sets the value of AssignedBy.
func (s *Signal) SetAssignedBy(val OptAssignedBy) {
	s.AssignedBy = val
}

// Ref: #/components/schemas/SignalKind
type SignalKind string

const (
	SignalKindEmail         SignalKind = "email"
	SignalKindMessage       SignalKind = "message"
	SignalKindCalendarEvent SignalKind = "calendar_event"
	SignalKindFile          SignalKind = "file"
)

// AllValues returns all SignalKind values.
func (SignalKind) AllValues() []SignalKind {
	return []SignalKind{
		SignalKindEmail,
		SignalKindMessage,
		SignalKindCalendarEvent,
		SignalKindFile,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SignalKind) MarshalText() ([]byte, error) {
	switch s {
	case SignalKindEmail:
		return []byte(s), nil
	case SignalKindMessage:
		return []byte(s), nil
	case SignalKindCalendarEvent:
		return []byte(s), nil
	case SignalKindFile:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SignalKind) UnmarshalText(data []byte) error {
	switch SignalKind(data) {
	case SignalKindEmail:
		*s = SignalKindEmail
		return nil
	case SignalKindMessage:
		*s = SignalKindMessage
		return nil
	case SignalKindCalendarEvent:
		*s = SignalKindCalendarEvent
		return nil
	case SignalKindFile:
		*s = SignalKindFile
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SignalList
type SignalList struct {
	Items []Signal `json:"items"`
}

// GetItems returns the value of Items.
func (s *SignalList) GetItems() []Signal {
	return s.Items
}

// SetItems sets the value of Items.
func (s *SignalList) SetItems(val []Signal) {
	s.Items = val
}

// Ref: #/components/schemas/SignedInUser
type SignedInUser struct {
	ID uuid.UUID `json:"id"`
	// The canonical address the owner declares. Not what authenticates them — sign-in matches on the
	// provider's immutable subject.
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	// Presentation only. Everything is stored and returned in UTC.
	Timezone string `json:"timezone"`
}

// GetID returns the value of ID.
func (s *SignedInUser) GetID() uuid.UUID {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *SignedInUser) GetEmail() string {
	return s.Email
}

// GetDisplayName returns the value of DisplayName.
func (s *SignedInUser) GetDisplayName() string {
	return s.DisplayName
}

// GetTimezone returns the value of Timezone.
func (s *SignedInUser) GetTimezone() string {
	return s.Timezone
}

// SetID sets the value of ID.
func (s *SignedInUser) SetID(val uuid.UUID) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *SignedInUser) SetEmail(val string) {
	s.Email = val
}

// SetDisplayName sets the value of DisplayName.
func (s *SignedInUser) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetTimezone sets the value of Timezone.
func (s *SignedInUser) SetTimezone(val string) {
	s.Timezone = val
}

// StartGoogleSignInFound is response for StartGoogleSignIn operation.
type StartGoogleSignInFound struct {
	Location  string
	SetCookie OptString
}

// GetLocation returns the value of Location.
func (s *StartGoogleSignInFound) GetLocation() string {
	return s.Location
}

// GetSetCookie returns the value of SetCookie.
func (s *StartGoogleSignInFound) GetSetCookie() OptString {
	return s.SetCookie
}

// SetLocation sets the value of Location.
func (s *StartGoogleSignInFound) SetLocation(val string) {
	s.Location = val
}

// SetSetCookie sets the value of SetCookie.
func (s *StartGoogleSignInFound) SetSetCookie(val OptString) {
	s.SetCookie = val
}

type UnlinkAuthProviderConflict ErrorEnvelope

func (*UnlinkAuthProviderConflict) unlinkAuthProviderRes() {}

// UnlinkAuthProviderNoContent is response for UnlinkAuthProvider operation.
type UnlinkAuthProviderNoContent struct{}

func (*UnlinkAuthProviderNoContent) unlinkAuthProviderRes() {}

type UnlinkAuthProviderNotFound ErrorEnvelope

func (*UnlinkAuthProviderNotFound) unlinkAuthProviderRes() {}

type UnlinkAuthProviderUnauthorized ErrorEnvelope

func (*UnlinkAuthProviderUnauthorized) unlinkAuthProviderRes() {}
