// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetContext implements getContext operation.
	//
	// Get one context.
	//
	// GET /api/v1/contexts/{contextId}
	GetContext(ctx context.Context, params GetContextParams) (GetContextRes, error)
	// ListAccounts implements listAccounts operation.
	//
	// Every account carries a `reliability` tier. A client must show it wherever it shows data derived
	// from that account: a report generated while a source was failing is never silently trusted.
	//
	// GET /api/v1/accounts
	ListAccounts(ctx context.Context, params ListAccountsParams) (*AccountList, error)
	// ListContexts implements listContexts operation.
	//
	// Returns the context tree, parents before children, then by position.
	//
	// GET /api/v1/contexts
	ListContexts(ctx context.Context, params ListContextsParams) (*ContextList, error)
	// ListSignals implements listSignals operation.
	//
	// `contextIds` is required. There is deliberately no unfiltered signal listing: a client that could
	// ask for everything would eventually show coursework during a client work session.
	//
	// Newest first, by the time the item actually occurred — not the time it was ingested, which is an
	// artefact of when a sync last ran.
	//
	// GET /api/v1/signals
	ListSignals(ctx context.Context, params ListSignalsParams) (*SignalList, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
