// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetContextParams is parameters of getContext operation.
type GetContextParams struct {
	ContextId uuid.UUID
}

func unpackGetContextParams(packed middleware.Parameters) (params GetContextParams) {
	{
		key := middleware.ParameterKey{
			Name: "contextId",
			In:   "path",
		}
		params.ContextId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetContextParams(args [1]string, argsEscaped bool, r *http.Request) (params GetContextParams, _ error) {
	// Decode path: contextId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "contextId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ContextId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "contextId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListAccountsParams is parameters of listAccounts operation.
type ListAccountsParams struct {
	// Only accounts feeding this context.
	ContextId OptUUID `json:",omitempty,omitzero"`
}

func unpackListAccountsParams(packed middleware.Parameters) (params ListAccountsParams) {
	{
		key := middleware.ParameterKey{
			Name: "contextId",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ContextId = v.(OptUUID)
		}
	}
	return params
}

func decodeListAccountsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListAccountsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: contextId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "contextId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotContextIdVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotContextIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ContextId.SetTo(paramsDotContextIdVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "contextId",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListContextsParams is parameters of listContexts operation.
type ListContextsParams struct {
	// Include archived contexts. Off by default.
	IncludeArchived OptBool `json:",omitempty,omitzero"`
}

func unpackListContextsParams(packed middleware.Parameters) (params ListContextsParams) {
	{
		key := middleware.ParameterKey{
			Name: "includeArchived",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeArchived = v.(OptBool)
		}
	}
	return params
}

func decodeListContextsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListContextsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: includeArchived.
	{
		val := bool(false)
		params.IncludeArchived.SetTo(val)
	}
	// Decode query: includeArchived.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "includeArchived",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeArchivedVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeArchivedVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeArchived.SetTo(paramsDotIncludeArchivedVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "includeArchived",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListSignalsParams is parameters of listSignals operation.
type ListSignalsParams struct {
	// One or more context ids. At least one is required.
	ContextIds []uuid.UUID `json:",omitempty"`
	// Return signals that occurred strictly before this instant.
	Before OptDateTime `json:",omitempty,omitzero"`
	Limit  OptInt32    `json:",omitempty,omitzero"`
}

func unpackListSignalsParams(packed middleware.Parameters) (params ListSignalsParams) {
	{
		key := middleware.ParameterKey{
			Name: "contextIds",
			In:   "query",
		}
		params.ContextIds = packed[key].([]uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "before",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Before = v.(OptDateTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt32)
		}
	}
	return params
}

func decodeListSignalsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListSignalsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: contextIds.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "contextIds",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				params.ContextIds = nil
				return d.DecodeArray(func(d uri.Decoder) error {
					var paramsDotContextIdsVal uuid.UUID
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToUUID(val)
						if err != nil {
							return err
						}

						paramsDotContextIdsVal = c
						return nil
					}(); err != nil {
						return err
					}
					params.ContextIds = append(params.ContextIds, paramsDotContextIdsVal)
					return nil
				})
			}); err != nil {
				return err
			}
			if err := func() error {
				if params.ContextIds == nil {
					return errors.New("nil is invalid value")
				}
				if err := (validate.Array{
					MinLength:    1,
					MinLengthSet: true,
					MaxLength:    50,
					MaxLengthSet: true,
				}).ValidateLength(len(params.ContextIds)); err != nil {
					return errors.Wrap(err, "array")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "contextIds",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: before.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "before",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotBeforeVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotBeforeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Before.SetTo(paramsDotBeforeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "before",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int32(50)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int32
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt32(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           200,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
