-- Foundation: the tables Phase 1 needs to see the world.
--
-- Scope is context document §6.1 only. Derived work items (§6.2), memory
-- (§6.3), and execution control (§6.4) belong to later phases and are not
-- created here — see CLAUDE.md, Phase discipline.
--
-- Conventions enforced throughout (docs/conventions.md §3):
--   * uuid primary keys, generated by the application, no database default
--   * timestamptz, always UTC; no timezone name appears in this file
--   * enum-like columns are text + CHECK, never native ENUM

-- +goose Up

-- +goose StatementBegin
CREATE EXTENSION IF NOT EXISTS vector;
-- +goose StatementEnd

-- Single row in practice. Present so multi-user is not a rewrite.
CREATE TABLE users (
    id           uuid PRIMARY KEY,
    email        text        NOT NULL,
    display_name text        NOT NULL,
    created_at   timestamptz NOT NULL,
    updated_at   timestamptz NOT NULL,
    CONSTRAINT users_email_unique UNIQUE (email)
);

-- The tree everything else hangs from.
CREATE TABLE contexts (
    id           uuid PRIMARY KEY,
    user_id      uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    parent_id    uuid        REFERENCES contexts (id) ON DELETE RESTRICT,
    name         text        NOT NULL,
    kind         text        NOT NULL,
    -- Weekday -> [{start_minute, end_minute}]. Empty means always active.
    active_hours jsonb       NOT NULL DEFAULT '{}'::jsonb,
    tone_profile text        NOT NULL DEFAULT '',
    is_archived  boolean     NOT NULL DEFAULT false,
    created_at   timestamptz NOT NULL,
    updated_at   timestamptz NOT NULL,
    CONSTRAINT contexts_kind_check CHECK (kind IN ('work', 'study', 'personal')),
    CONSTRAINT contexts_not_own_parent CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT contexts_name_unique UNIQUE (user_id, name)
);

CREATE INDEX contexts_parent_idx ON contexts (parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX contexts_active_idx ON contexts (user_id) WHERE NOT is_archived;

-- reliability is a first-class column, not a derived label: the interface must
-- mark data that came from a source which may be incomplete.
CREATE TABLE accounts (
    id              uuid PRIMARY KEY,
    user_id         uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    provider        text        NOT NULL,
    reliability     text        NOT NULL,
    display_name    text        NOT NULL,
    -- Encrypted at rest with CREDENTIALS_ENCRYPTION_KEY. Never logged, never
    -- returned by an API response, never placed in a prompt.
    credentials_enc jsonb       NOT NULL DEFAULT '{}'::jsonb,
    status          text        NOT NULL DEFAULT 'disconnected',
    last_sync_at    timestamptz,
    last_error      text        NOT NULL DEFAULT '',
    created_at      timestamptz NOT NULL,
    updated_at      timestamptz NOT NULL,
    CONSTRAINT accounts_provider_check CHECK (
        provider IN ('gmail', 'google_calendar', 'google_drive', 'zalo_oa', 'manual')
    ),
    CONSTRAINT accounts_reliability_check CHECK (reliability IN ('official', 'unofficial', 'manual')),
    CONSTRAINT accounts_status_check CHECK (status IN ('connected', 'error', 'disconnected')),
    CONSTRAINT accounts_name_unique UNIQUE (user_id, provider, display_name)
);

-- One Gmail account can feed several contexts; the router decides per signal.
CREATE TABLE account_contexts (
    account_id uuid NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    context_id uuid NOT NULL REFERENCES contexts (id) ON DELETE CASCADE,
    PRIMARY KEY (account_id, context_id)
);

CREATE INDEX account_contexts_context_idx ON account_contexts (context_id);

-- Rules resolve routing before a model call. Most traffic never reaches a model.
CREATE TABLE routing_rules (
    id          uuid PRIMARY KEY,
    context_id  uuid        NOT NULL REFERENCES contexts (id) ON DELETE CASCADE,
    match_type  text        NOT NULL,
    match_value text        NOT NULL,
    priority    integer     NOT NULL DEFAULT 100,
    is_active   boolean     NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL,
    CONSTRAINT routing_rules_match_type_check CHECK (
        match_type IN ('sender', 'domain', 'keyword', 'thread')
    ),
    CONSTRAINT routing_rules_value_not_blank CHECK (length(btrim(match_value)) > 0),
    CONSTRAINT routing_rules_unique UNIQUE (context_id, match_type, match_value)
);

CREATE INDEX routing_rules_lookup_idx ON routing_rules (match_type, priority) WHERE is_active;

-- Immutable. See the trigger below: this is enforced by the database, not only
-- by convention, because everything else in Warp is derived from these rows.
CREATE TABLE signals (
    id           uuid PRIMARY KEY,
    account_id   uuid        NOT NULL REFERENCES accounts (id) ON DELETE RESTRICT,
    external_id  text        NOT NULL,
    kind         text        NOT NULL,
    payload      jsonb       NOT NULL,
    content_hash text        NOT NULL,
    occurred_at  timestamptz NOT NULL,
    ingested_at  timestamptz NOT NULL,
    processed_at timestamptz,
    CONSTRAINT signals_kind_check CHECK (kind IN ('email', 'message', 'calendar_event', 'file')),
    -- Idempotent ingestion: re-running a sync is a no-op.
    CONSTRAINT signals_external_unique UNIQUE (account_id, external_id)
);

CREATE INDEX signals_occurred_idx ON signals (occurred_at DESC);
CREATE INDEX signals_unprocessed_idx ON signals (ingested_at) WHERE processed_at IS NULL;
-- The extraction cache key.
CREATE INDEX signals_content_hash_idx ON signals (content_hash);

-- +goose StatementBegin
CREATE FUNCTION signals_reject_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'signals are immutable: delete of % is not allowed', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;

    IF NEW.account_id  IS DISTINCT FROM OLD.account_id
    OR NEW.external_id IS DISTINCT FROM OLD.external_id
    OR NEW.kind        IS DISTINCT FROM OLD.kind
    OR NEW.payload     IS DISTINCT FROM OLD.payload
    OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
    OR NEW.occurred_at IS DISTINCT FROM OLD.occurred_at
    OR NEW.ingested_at IS DISTINCT FROM OLD.ingested_at THEN
        RAISE EXCEPTION 'signals are immutable: only processed_at may change (signal %)', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER signals_immutable
    BEFORE UPDATE OR DELETE ON signals
    FOR EACH ROW EXECUTE FUNCTION signals_reject_mutation();

-- One signal placed in one context, with what decided it.
CREATE TABLE signal_contexts (
    signal_id   uuid             NOT NULL REFERENCES signals (id) ON DELETE CASCADE,
    context_id  uuid             NOT NULL REFERENCES contexts (id) ON DELETE CASCADE,
    confidence  double precision NOT NULL,
    assigned_by text             NOT NULL,
    created_at  timestamptz      NOT NULL,
    PRIMARY KEY (signal_id, context_id),
    CONSTRAINT signal_contexts_assigned_by_check CHECK (assigned_by IN ('rule', 'model', 'manual')),
    CONSTRAINT signal_contexts_confidence_range CHECK (confidence >= 0 AND confidence <= 1)
);

-- The session-scoped read path: everything the owner sees is filtered by context.
CREATE INDEX signal_contexts_context_idx ON signal_contexts (context_id, signal_id);
-- Routing quality review: which model assignments were least certain.
CREATE INDEX signal_contexts_low_confidence_idx ON signal_contexts (confidence)
    WHERE assigned_by = 'model';

CREATE TABLE people (
    id           uuid PRIMARY KEY,
    user_id      uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    display_name text        NOT NULL,
    notes        text        NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL,
    updated_at   timestamptz NOT NULL
);

-- Links one person across an email address, a Zalo ID, and a phone number.
CREATE TABLE identities (
    id        uuid PRIMARY KEY,
    person_id uuid    NOT NULL REFERENCES people (id) ON DELETE CASCADE,
    provider  text    NOT NULL,
    handle    text    NOT NULL,
    verified  boolean NOT NULL DEFAULT false,
    CONSTRAINT identities_provider_check CHECK (
        provider IN ('gmail', 'google_calendar', 'google_drive', 'zalo_oa', 'manual')
    ),
    CONSTRAINT identities_handle_unique UNIQUE (provider, handle)
);

CREATE INDEX identities_person_idx ON identities (person_id);

-- +goose Down

DROP TABLE IF EXISTS identities;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS signal_contexts;
DROP TRIGGER IF EXISTS signals_immutable ON signals;
DROP FUNCTION IF EXISTS signals_reject_mutation();
DROP TABLE IF EXISTS signals;
DROP TABLE IF EXISTS routing_rules;
DROP TABLE IF EXISTS account_contexts;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS contexts;
DROP TABLE IF EXISTS users;
