/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account with an email and password
         * @description Unrestricted. Warp runs on the owner's own machine, so there is no
         *     stranger to keep out.
         *
         *     What remains out of scope is multi-user *behaviour* — no teams, no
         *     sharing, no permissions. Two tables, `action_types` and
         *     `prompt_templates`, carry no `user_id` and would be shared config if a
         *     second account existed.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with an email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin signing in with Google
         * @description Redirects to Google. Sets a short-lived, `HttpOnly` state cookie that the
         *     callback checks, which is what stops a forged callback from signing
         *     someone in.
         *
         *     Scopes are `openid email profile` only. This grants no access to mail or
         *     calendar — connecting those is a separate consent, and lives with
         *     `accounts`.
         */
        get: operations["startGoogleSignIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finish signing in with Google
         * @description Where Google returns the browser. Verifies `state` against the cookie,
         *     exchanges `code`, and matches the resulting `sub` claim against
         *     `auth_providers`. Matching is on `sub`, never on the email address: an
         *     email can be reassigned at the provider, and matching on it would hand
         *     the account to whoever inherits it.
         *
         *     An identity that is not already linked is rejected. There is exactly one
         *     owner, and sign-in does not create accounts.
         *
         *     On success, sets the session cookie and redirects to `returnTo`.
         */
        get: operations["completeGoogleSignIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is signed in, and on what */
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        /**
         * Sign out of this browser
         * @description Revokes this session only. Other browsers stay signed in — use
         *     `/auth/sessions/{sessionId}` to revoke one of those.
         */
        delete: operations["signOut"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every browser currently signed in
         * @description Sessions are server-side precisely so this list can exist and be acted
         *     on. A lost laptop is revoked from here, without rotating anything.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one session */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The ways the owner can sign in
         * @description More than one is the point. A single way in is a single point of lockout,
         *     and there is no administrator to appeal to.
         */
        get: operations["listAuthProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/providers/{providerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unlink a sign-in method
         * @description Refuses to remove the last one — that is an unrecoverable lockout, and
         *     the database enforces it as well as this endpoint.
         */
        delete: operations["unlinkAuthProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List contexts
         * @description Returns the context tree, parents before children, then by position.
         */
        get: operations["listContexts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{contextId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one context */
        get: operations["getContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List connected accounts
         * @description Every account carries a `reliability` tier. A client must show it
         *     wherever it shows data derived from that account: a report generated
         *     while a source was failing is never silently trusted.
         */
        get: operations["listAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signal timeline for one or more contexts
         * @description `contextIds` is required. There is deliberately no unfiltered signal
         *     listing: a client that could ask for everything would eventually show
         *     coursework during a client work session.
         *
         *     Newest first, by the time the item actually occurred — not the time it
         *     was ingested, which is an artefact of when a sync last ran.
         */
        get: operations["listSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a task by hand
         * @description The manual path in, and a first-class one: a task decided in a meeting
         *     leaves no signal to extract from, and losing it is worse than recording
         *     it without a source.
         *
         *     What manual entry never does is pretend to be derived. `sourceSignalId`
         *     is absent from the request on purpose — extraction sets it through the
         *     service, and a hand-written task that could claim an email as its origin
         *     would make the audit trail lie.
         *
         *     Three more fields are the server's to decide, not the client's: `id` is
         *     a UUIDv7 generated before insert, `userId` comes from the session cookie
         *     and never from the body, and `status` always starts `open`. Creating a
         *     task that is already done is a create followed by a status change —
         *     `completedAt` and `blockedReason` are consequences of that status, which
         *     is why they are set by the status transition and not stated here.
         *
         *     `owner` is absent until Phase 3. The column accepts `agent`, but no
         *     agent runs yet, so a task assigned to one would sit in a queue nothing
         *     drains.
         */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commitments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a promise by hand
         * @description Most hand-recorded commitments come from a phone call, which leaves no
         *     signal at all. That is the case this endpoint exists for.
         *
         *     `evidenceSignalId` is absent, and this is the sharpest instance of that
         *     rule anywhere in the API. A commitment is worth what its evidence is
         *     worth: the owner clicks it and reads the exact sentence that created it.
         *     A client able to set that field could point a promise it invented at
         *     somebody's email — the trail would not merely be thin, it would be
         *     false.
         *
         *     `isConfirmed` is absent for a different reason: the server sets it
         *     `true` here. That column exists to mark what a model guessed, and holds
         *     back reminders until the owner agrees. A promise the owner just typed is
         *     confirmed by the act of typing it. Extraction takes the other path and
         *     writes `false`.
         *
         *     As with tasks, `id`, `userId` and `status` are the server's. `status`
         *     starts `open`, and `resolvedAt` is a consequence of leaving that state
         *     rather than something a client states — the two are checked against each
         *     other by `commitments_resolution_consistent`.
         */
        post: operations["createCommitment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Every error this API returns has this shape, so a client has exactly one
         *     branch to write.
         */
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        Error: {
            /**
             * @description Stable, machine-readable. Safe to switch on.
             * @example not_found
             */
            code: string;
            /**
             * @description Human-readable and safe to display. Never contains payload
             *     contents, credentials, or anyone's correspondence.
             * @example context not found
             */
            message: string;
            /** @description Structured detail, when there is any that is safe to return. */
            details?: {
                [key: string]: unknown;
            };
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /**
             * Format: password
             * @description Length is the only rule the contract enforces. Composition rules
             *     push people towards predictable substitutions; length does not.
             */
            password: string;
            displayName: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        /**
         * @description How a sign-in method authenticates. `zalo` and `facebook` are sign-in
         *     products distinct from their messaging APIs — linking one grants no
         *     access to messages.
         * @enum {string}
         */
        AuthProviderKind: "google" | "zalo" | "facebook" | "passkey" | "password";
        LinkedProvider: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["AuthProviderKind"];
            /**
             * @description What the provider reported when this was linked. Display only — it
             *     is not what authenticates, and a passkey has none.
             */
            email?: string;
            isPrimary: boolean;
            /** Format: date-time */
            linkedAt: string;
            /** Format: date-time */
            lastLoginAt?: string | null;
        };
        LinkedProviderList: {
            items: components["schemas"]["LinkedProvider"][];
        };
        /**
         * @description A browser that is signed in. The token itself never appears here — only
         *     the server-side record of it.
         */
        Session: {
            /** Format: uuid */
            id: string;
            providerKind?: components["schemas"]["AuthProviderKind"];
            /** Format: date-time */
            issuedAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description Enough to recognise which browser this is, and revoke the right one. */
            userAgent?: string;
            ip?: string | null;
            /** @description True for the session making this request. */
            isCurrent: boolean;
        };
        SessionList: {
            items: components["schemas"]["Session"][];
        };
        SignedInUser: {
            /** Format: uuid */
            id: string;
            /**
             * @description The canonical address the owner declares. Not what authenticates
             *     them — sign-in matches on the provider's immutable subject.
             */
            email: string;
            displayName: string;
            /**
             * @description Presentation only. Everything is stored and returned in UTC.
             * @example Asia/Ho_Chi_Minh
             */
            timezone: string;
        };
        CurrentSession: {
            user: components["schemas"]["SignedInUser"];
            session: components["schemas"]["Session"];
        };
        /** @enum {string} */
        ContextKind: "work" | "study" | "personal";
        Context: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Null for a root context. A child inherits its parent's defaults.
             */
            parentId?: string | null;
            /** @example job-a */
            slug: string;
            /** @example Remote job A */
            name: string;
            kind: components["schemas"]["ContextKind"];
            color?: string | null;
            /** @description How the system writes on the owner's behalf in this context. */
            toneProfile?: string;
            /**
             * Format: int32
             * @description Display order among siblings.
             */
            position: number;
            isArchived: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ContextList: {
            items: components["schemas"]["Context"][];
        };
        /**
         * @description How complete this source can be assumed to be. Only `official` may be
         *     presented as the whole picture.
         * @enum {string}
         */
        Reliability: "official" | "unofficial" | "manual";
        /**
         * @description The account's health right now, as distinct from its reliability tier.
         * @enum {string}
         */
        AccountStatus: "connected" | "error" | "disconnected";
        Account: {
            /** Format: uuid */
            id: string;
            /** @example gmail */
            provider: string;
            reliability: components["schemas"]["Reliability"];
            displayName: string;
            status: components["schemas"]["AccountStatus"];
            /** Format: date-time */
            lastSyncAt?: string | null;
            /** @description Empty when healthy. Never contains credentials. */
            lastError?: string;
        };
        AccountList: {
            items: components["schemas"]["Account"][];
        };
        /** @enum {string} */
        SignalKind: "email" | "message" | "calendar_event" | "file";
        /**
         * @description What decided this signal's placement, so a misfiling can be traced.
         * @enum {string}
         */
        AssignedBy: "rule" | "model" | "manual";
        /**
         * @description A signal as the timeline shows it. `payload` is deliberately absent:
         *     the raw item stays in the database.
         */
        Signal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            kind: components["schemas"]["SignalKind"];
            subject?: string;
            /** @description A short excerpt, enough to recognise the item in a list. */
            snippet?: string;
            /**
             * Format: date-time
             * @description When the item actually happened, not when it was fetched.
             */
            occurredAt: string;
            /** Format: date-time */
            ingestedAt: string;
            /** @description Whether extraction has already run over this signal. */
            processed: boolean;
            /**
             * Format: uuid
             * @description The context this row was returned under.
             */
            contextId?: string;
            /**
             * Format: double
             * @description How certain the placement is. Always 1 for a rule match.
             */
            confidence?: number;
            assignedBy?: components["schemas"]["AssignedBy"];
        };
        SignalList: {
            items: components["schemas"]["Signal"][];
        };
        /**
         * @description `blocked` carries a reason and `done` carries a completion time — the
         *     database checks both, so a status is never on its own.
         * @enum {string}
         */
        TaskStatus: "open" | "in_progress" | "blocked" | "done" | "dropped";
        /**
         * @description Who is expected to do this. `agent` is not reachable before Phase 3;
         *     it is described here because the column exists, not because it works.
         * @enum {string}
         */
        TaskOwner: "me" | "agent";
        Task: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description The one context this task belongs to. Work spanning two contexts is
             *     two tasks — unlike a signal, which can legitimately land in both.
             */
            contextId: string;
            /**
             * Format: uuid
             * @description The signal extraction derived this from. Null for a task written by
             *     hand, and that null is the honest answer — it is what tells the
             *     owner nothing external vouches for this row.
             */
            sourceSignalId?: string | null;
            /** Format: uuid */
            parentTaskId?: string | null;
            /**
             * Format: uuid
             * @description The promise this task discharges, if any. Null for most tasks: work
             *     the owner set themselves has no counterparty waiting on it.
             */
            commitmentId?: string | null;
            title: string;
            detail?: string | null;
            status: components["schemas"]["TaskStatus"];
            owner: components["schemas"]["TaskOwner"];
            /**
             * Format: int32
             * @description 1 is most urgent.
             */
            priority: number;
            /**
             * Format: date-time
             * @description UTC. The browser converts to Asia/Ho_Chi_Minh, nothing else does.
             */
            dueAt?: string | null;
            /** Format: int32 */
            estimatedMinutes?: number | null;
            /** @description Present exactly when status is `blocked`. */
            blockedReason?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: date-time
             * @description Present exactly when status is `done`.
             */
            completedAt?: string | null;
        };
        /**
         * @description A task the owner writes by hand. Every field the server decides for
         *     itself is absent rather than optional — see the operation description.
         */
        CreateTaskRequest: {
            /**
             * Format: uuid
             * @description The one context this task belongs to. Work spanning two contexts is
             *     two tasks, not one task in two places.
             */
            contextId: string;
            /**
             * @description minLength mirrors `tasks_title_not_blank`. maxLength is stricter
             *     than the column, which is `text` — a 500-character title is a paste
             *     accident, and refusing it here beats storing it.
             */
            title: string;
            detail?: string | null;
            /**
             * Format: int32
             * @description 1 is most urgent. Range mirrors `tasks_priority_range`. The column
             *     also defaults to 3; the server resolves the value and always writes
             *     it explicitly, so the two defaults cannot drift apart unnoticed.
             * @default 3
             */
            priority: number;
            /**
             * Format: date-time
             * @description UTC. Conversion to Asia/Ho_Chi_Minh happens in the browser, never
             *     in a query and never here.
             */
            dueAt?: string | null;
            /**
             * Format: int32
             * @description Mirrors `tasks_estimate_positive` — zero is not an estimate.
             */
            estimatedMinutes?: number | null;
            /**
             * Format: uuid
             * @description Must be in the same context.
             */
            parentTaskId?: string | null;
            /**
             * Format: uuid
             * @description The promise this task discharges, if any. Most tasks have none.
             *     Must be in the same context — a composite foreign key enforces it,
             *     so a mismatch is a rejected write, not a silently wrong link.
             */
            commitmentId?: string | null;
        };
        /**
         * @description Who owes whom. Exactly two values, and there is no third case: either
         *     the owner promised someone, or someone promised the owner.
         *
         *     `owed_to_me` has no task equivalent — there is nothing for the owner to
         *     do, only someone to chase. That half is what most systems drop.
         * @enum {string}
         */
        CommitmentDirection: "i_owe" | "owed_to_me";
        /**
         * @description There is no `overdue` here. Overdue is derived from `dueAt` at read
         *     time, so it can never go stale in storage.
         * @enum {string}
         */
        CommitmentStatus: "open" | "fulfilled" | "waived" | "dropped";
        Commitment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            contextId: string;
            /**
             * Format: uuid
             * @description The counterparty. Null means incomplete, not invalid.
             */
            personId?: string | null;
            /**
             * Format: uuid
             * @description The signal carrying the promise, so the owner can read the exact
             *     sentence. Null for a commitment recorded by hand — which the UI says
             *     plainly rather than leaving the reader to assume evidence exists.
             */
            evidenceSignalId?: string | null;
            direction: components["schemas"]["CommitmentDirection"];
            what: string;
            status: components["schemas"]["CommitmentStatus"];
            /** Format: date-time */
            promisedAt: string;
            /** Format: date-time */
            dueAt?: string | null;
            /**
             * Format: date-time
             * @description Present exactly when status is not `open`.
             */
            resolvedAt?: string | null;
            /**
             * @description Whether the owner has agreed this promise is real. False for a fresh
             *     extraction, and false is what holds reminders back until precision
             *     has been measured. True for anything recorded by hand.
             */
            isConfirmed: boolean;
            /**
             * @description Derived from `dueAt` at read time, never stored. Computed by the
             *     server so that "overdue" does not depend on the clock or timezone of
             *     whichever browser is asking.
             */
            isOverdue: boolean;
            /**
             * Format: int32
             * @description Null when there is no due date.
             */
            daysOverdue?: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description A promise the owner records by hand — most often one made on a phone
         *     call, which leaves no signal to extract from.
         */
        CreateCommitmentRequest: {
            /** Format: uuid */
            contextId: string;
            direction: components["schemas"]["CommitmentDirection"];
            /**
             * @description The promise in the owner's own words. minLength mirrors
             *     `commitments_what_not_blank`. A commitment is one sentence — if it
             *     needs more, it is several commitments.
             * @example Gửi báo giá thiết bị
             */
            what: string;
            /**
             * Format: uuid
             * @description The counterparty. Nullable so that recording a promise never blocks
             *     on creating a person first: the minute a call ends is the minute it
             *     gets forgotten. A commitment without one is incomplete rather than
             *     invalid, and the board surfaces it as something to fill in.
             */
            personId?: string | null;
            /**
             * Format: date-time
             * @description When the promise was actually made, UTC. Defaults to now. Sent
             *     explicitly when recording something from earlier — a call on Monday
             *     entered on Wednesday is not a promise made on Wednesday.
             */
            promisedAt?: string | null;
            /** Format: date-time */
            dueAt?: string | null;
        };
    };
    responses: {
        /** @description The request failed. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No valid session. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        ContextId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The owner was created and is now signed in. */
            201: {
                headers: {
                    /** @description The session cookie — `HttpOnly`, `Secure`, `SameSite=Lax`. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentSession"];
                };
            };
            /**
             * @description That email is already registered. Reported from the unique
             *     constraint rather than a prior lookup, so two simultaneous
             *     registrations cannot both pass a check and then collide.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    /** @description The session cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentSession"];
                };
            };
            /**
             * @description Wrong email or password. Deliberately one response for both, so the
             *     endpoint cannot be used to discover which addresses exist.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too many failed attempts; the account is temporarily locked. */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startGoogleSignIn: {
        parameters: {
            query?: {
                /**
                 * @description Where to land after signing in. A path within this application only:
                 *     the pattern rejects an absolute URL and a protocol-relative `//host`,
                 *     so this cannot become an open redirect.
                 */
                returnTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google's consent screen. */
            302: {
                headers: {
                    Location: string;
                    /** @description The `HttpOnly` state cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    completeGoogleSignIn: {
        parameters: {
            query: {
                code: string;
                state: string;
                /** @description Present when the owner declined at Google's consent screen. */
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed in; redirecting into the application. */
            302: {
                headers: {
                    Location: string;
                    /** @description The session cookie — `HttpOnly`, `Secure`, `SameSite=Lax`. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            default: components["responses"]["Error"];
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session and the owner it belongs to. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentSession"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            default: components["responses"]["Error"];
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            204: {
                headers: {
                    /** @description The session cookie, expired. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            default: components["responses"]["Error"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live sessions, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            default: components["responses"]["Error"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. Already-revoked sessions also return 204. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    listAuthProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Linked sign-in methods. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkedProviderList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            default: components["responses"]["Error"];
        };
    };
    unlinkAuthProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unlinked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /** @description This is the only way in left. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listContexts: {
        parameters: {
            query?: {
                /** @description Include archived contexts. Off by default. */
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The context tree. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contextId: components["parameters"]["ContextId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The context. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Context"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Error"];
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                /** @description Only accounts feeding this context. */
                contextId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The connected accounts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSignals: {
        parameters: {
            query: {
                /** @description One or more context ids. At least one is required. */
                contextIds: string[];
                /** @description Return signals that occurred strictly before this instant. */
                before?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the timeline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /**
             * @description The task as stored, including every value the server decided. The
             *     query underneath is `INSERT ... RETURNING *`, so the whole row costs
             *     no extra round trip and spares the client a follow-up `GET`.
             */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /**
             * @description No such context, or one belonging to someone else. The two are
             *     reported identically: a context the owner cannot see does not exist.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description A rule the schema could not express on its own — a parent task or
             *     commitment in a different context, most often. Cross-context links
             *     are refused by a composite foreign key in the database, so this is
             *     a rejected write rather than a silently wrong row.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createCommitment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommitmentRequest"];
            };
        };
        responses: {
            /** @description The commitment as stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Commitment"];
                };
            };
            /** @description No such context or person, or one belonging to someone else. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A person or context that does not line up with the other. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
