// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearFailedLogins = `-- name: ClearFailedLogins :exec
UPDATE auth_passwords
SET failed_attempts = 0, locked_until = NULL
WHERE auth_provider_id = $1
`

func (q *Queries) ClearFailedLogins(ctx context.Context, authProviderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearFailedLogins, authProviderID)
	return err
}

const countAuthProviders = `-- name: CountAuthProviders :one
SELECT count(*) FROM auth_providers WHERE user_id = $1
`

func (q *Queries) CountAuthProviders(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthProviders, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthPassword = `-- name: CreateAuthPassword :exec
INSERT INTO auth_passwords (auth_provider_id, hash) VALUES ($1, $2)
`

type CreateAuthPasswordParams struct {
	AuthProviderID uuid.UUID
	Hash           string
}

func (q *Queries) CreateAuthPassword(ctx context.Context, arg CreateAuthPasswordParams) error {
	_, err := q.db.Exec(ctx, createAuthPassword, arg.AuthProviderID, arg.Hash)
	return err
}

const createAuthProvider = `-- name: CreateAuthProvider :one
INSERT INTO auth_providers (id, user_id, kind, subject, email, is_primary)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, kind, subject, email, is_primary, linked_at, last_login_at
`

type CreateAuthProviderParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      AuthProviderKind
	Subject   string
	Email     *string
	IsPrimary bool
}

func (q *Queries) CreateAuthProvider(ctx context.Context, arg CreateAuthProviderParams) (AuthProvider, error) {
	row := q.db.QueryRow(ctx, createAuthProvider,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Subject,
		arg.Email,
		arg.IsPrimary,
	)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Subject,
		&i.Email,
		&i.IsPrimary,
		&i.LinkedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (id, user_id, auth_provider_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, auth_provider_id, token_hash, issued_at, last_seen_at, expires_at, revoked_at, user_agent, ip
`

type CreateAuthSessionParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	AuthProviderID *uuid.UUID
	TokenHash      []byte
	ExpiresAt      pgtype.Timestamptz
	UserAgent      string
	Ip             *netip.Addr
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.AuthProviderID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthProviderID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id) VALUES ($1) RETURNING id, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, createUser, id)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (user_id, email, display_name)
VALUES ($1, $2, $3)
RETURNING user_id, email, display_name, timezone, created_at, updated_at
`

type CreateUserProfileParams struct {
	UserID      uuid.UUID
	Email       string
	DisplayName string
}

// Timezone is deliberately absent: the column default is the single place that
// value is written down.
func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile, arg.UserID, arg.Email, arg.DisplayName)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthProvider = `-- name: DeleteAuthProvider :execrows
DELETE FROM auth_providers WHERE id = $1 AND user_id = $2
`

type DeleteAuthProviderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// DeleteAuthProvider is scoped to the user so an id from elsewhere cannot be
// used to unlink someone else's. Removing the last one raises
// restrict_violation from a trigger; the service turns that into a conflict.
func (q *Queries) DeleteAuthProvider(ctx context.Context, arg DeleteAuthProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthProvider, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasswordCredential = `-- name: GetPasswordCredential :one
SELECT p.id   AS provider_id,
       p.user_id,
       p.subject,
       w.hash,
       w.failed_attempts,
       w.locked_until
FROM auth_providers p
JOIN auth_passwords w ON w.auth_provider_id = p.id
WHERE p.kind = 'password' AND p.subject = $1
`

type GetPasswordCredentialRow struct {
	ProviderID     uuid.UUID
	UserID         uuid.UUID
	Subject        string
	Hash           string
	FailedAttempts int16
	LockedUntil    pgtype.Timestamptz
}

// GetPasswordCredential is the whole of what a password sign-in needs, in one
// round trip: the identity, the hash, and the lockout state.
//
// `subject` for a password identity is the normalised email — it is the login
// identifier, the same role the `sub` claim plays for Google.
func (q *Queries) GetPasswordCredential(ctx context.Context, email string) (GetPasswordCredentialRow, error) {
	row := q.db.QueryRow(ctx, getPasswordCredential, email)
	var i GetPasswordCredentialRow
	err := row.Scan(
		&i.ProviderID,
		&i.UserID,
		&i.Subject,
		&i.Hash,
		&i.FailedAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, email, display_name, timezone, created_at, updated_at FROM user_profiles WHERE user_id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, userID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthProviders = `-- name: ListAuthProviders :many
SELECT id, user_id, kind, subject, email, is_primary, linked_at, last_login_at FROM auth_providers
WHERE user_id = $1
ORDER BY is_primary DESC, linked_at
`

func (q *Queries) ListAuthProviders(ctx context.Context, userID uuid.UUID) ([]AuthProvider, error) {
	rows, err := q.db.Query(ctx, listAuthProviders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthProvider{}
	for rows.Next() {
		var i AuthProvider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Subject,
			&i.Email,
			&i.IsPrimary,
			&i.LinkedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSessions = `-- name: ListLiveSessions :many
SELECT s.id, s.user_id, s.auth_provider_id, s.token_hash, s.issued_at, s.last_seen_at, s.expires_at, s.revoked_at, s.user_agent, s.ip, p.kind AS provider_kind
FROM auth_sessions s
LEFT JOIN auth_providers p ON p.id = s.auth_provider_id
WHERE s.user_id = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > $2::timestamptz
ORDER BY s.last_seen_at DESC
`

type ListLiveSessionsParams struct {
	UserID uuid.UUID
	Now    pgtype.Timestamptz
}

type ListLiveSessionsRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	AuthProviderID *uuid.UUID
	TokenHash      []byte
	IssuedAt       pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	UserAgent      string
	Ip             *netip.Addr
	ProviderKind   *AuthProviderKind
}

// ListLiveSessions is what makes a lost laptop revocable: it exists so the
// owner can see where they are signed in and end one of them.
func (q *Queries) ListLiveSessions(ctx context.Context, arg ListLiveSessionsParams) ([]ListLiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listLiveSessions, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveSessionsRow{}
	for rows.Next() {
		var i ListLiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthProviderID,
			&i.TokenHash,
			&i.IssuedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.UserAgent,
			&i.Ip,
			&i.ProviderKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveSessionByTokenHash = `-- name: LiveSessionByTokenHash :one
SELECT s.id, s.user_id, s.auth_provider_id, s.token_hash, s.issued_at, s.last_seen_at, s.expires_at, s.revoked_at, s.user_agent, s.ip, p.kind AS provider_kind
FROM auth_sessions s
LEFT JOIN auth_providers p ON p.id = s.auth_provider_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > $2::timestamptz
`

type LiveSessionByTokenHashParams struct {
	TokenHash []byte
	Now       pgtype.Timestamptz
}

type LiveSessionByTokenHashRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	AuthProviderID *uuid.UUID
	TokenHash      []byte
	IssuedAt       pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	UserAgent      string
	Ip             *netip.Addr
	ProviderKind   *AuthProviderKind
}

// LiveSessionByTokenHash resolves the cookie on every authenticated request.
// Expiry and revocation are part of the predicate, so a caller cannot forget to
// check them.
func (q *Queries) LiveSessionByTokenHash(ctx context.Context, arg LiveSessionByTokenHashParams) (LiveSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, liveSessionByTokenHash, arg.TokenHash, arg.Now)
	var i LiveSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthProviderID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
		&i.ProviderKind,
	)
	return i, err
}

const markProviderUsed = `-- name: MarkProviderUsed :exec
UPDATE auth_providers SET last_login_at = $2 WHERE id = $1
`

type MarkProviderUsedParams struct {
	ID          uuid.UUID
	LastLoginAt pgtype.Timestamptz
}

func (q *Queries) MarkProviderUsed(ctx context.Context, arg MarkProviderUsedParams) error {
	_, err := q.db.Exec(ctx, markProviderUsed, arg.ID, arg.LastLoginAt)
	return err
}

const providerByKindSubject = `-- name: ProviderByKindSubject :one
SELECT id, user_id, kind, subject, email, is_primary, linked_at, last_login_at FROM auth_providers WHERE kind = $1 AND subject = $2
`

type ProviderByKindSubjectParams struct {
	Kind    AuthProviderKind
	Subject string
}

// ProviderByKindSubject resolves a federated identity. Matching is on the
// provider's immutable subject, never the email.
func (q *Queries) ProviderByKindSubject(ctx context.Context, arg ProviderByKindSubjectParams) (AuthProvider, error) {
	row := q.db.QueryRow(ctx, providerByKindSubject, arg.Kind, arg.Subject)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Subject,
		&i.Email,
		&i.IsPrimary,
		&i.LinkedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const recordFailedLogin = `-- name: RecordFailedLogin :one
UPDATE auth_passwords
SET failed_attempts = failed_attempts + 1,
    locked_until = CASE
        WHEN failed_attempts + 1 >= $1::smallint THEN $2::timestamptz
        ELSE locked_until
    END
WHERE auth_provider_id = $3
RETURNING failed_attempts, locked_until
`

type RecordFailedLoginParams struct {
	MaxAttempts int16
	LockUntil   pgtype.Timestamptz
	ProviderID  uuid.UUID
}

type RecordFailedLoginRow struct {
	FailedAttempts int16
	LockedUntil    pgtype.Timestamptz
}

// RecordFailedLogin counts the attempt and locks the credential once the count
// reaches the threshold. Counted in the database rather than in Redis: a
// lockout that evaporates when the cache restarts is not a lockout.
func (q *Queries) RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) (RecordFailedLoginRow, error) {
	row := q.db.QueryRow(ctx, recordFailedLogin, arg.MaxAttempts, arg.LockUntil, arg.ProviderID)
	var i RecordFailedLoginRow
	err := row.Scan(&i.FailedAttempts, &i.LockedUntil)
	return i, err
}

const revokeSessionByID = `-- name: RevokeSessionByID :execrows
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, $1)
WHERE id = $2 AND user_id = $3
`

type RevokeSessionByIDParams struct {
	RevokedAt pgtype.Timestamptz
	SessionID uuid.UUID
	UserID    uuid.UUID
}

// RevokeSessionByID is idempotent for a session that belongs to the caller:
// COALESCE keeps the original revocation time, so the row still matches and the
// second call is a no-op rather than a miss. Zero rows therefore means "not
// yours", which is the only case worth a 404.
func (q *Queries) RevokeSessionByID(ctx context.Context, arg RevokeSessionByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByID, arg.RevokedAt, arg.SessionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :execrows
UPDATE auth_sessions
SET revoked_at = $1
WHERE token_hash = $2 AND revoked_at IS NULL
`

type RevokeSessionByTokenHashParams struct {
	RevokedAt pgtype.Timestamptz
	TokenHash []byte
}

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, arg RevokeSessionByTokenHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByTokenHash, arg.RevokedAt, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepExpiredSessions = `-- name: SweepExpiredSessions :execrows
DELETE FROM auth_sessions
WHERE expires_at < $1::timestamptz
   OR (revoked_at IS NOT NULL AND revoked_at < $1::timestamptz)
`

// SweepExpiredSessions removes rows that can no longer authenticate anything.
// Revoked rows are kept for a grace period rather than deleted immediately, so
// "when did I sign out" stays answerable for a while.
func (q *Queries) SweepExpiredSessions(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredSessions, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAuthSession = `-- name: TouchAuthSession :exec
UPDATE auth_sessions SET last_seen_at = $2 WHERE id = $1
`

type TouchAuthSessionParams struct {
	ID         uuid.UUID
	LastSeenAt pgtype.Timestamptz
}

func (q *Queries) TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) error {
	_, err := q.db.Exec(ctx, touchAuthSession, arg.ID, arg.LastSeenAt)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE auth_passwords SET hash = $2 WHERE auth_provider_id = $1
`

type UpdatePasswordHashParams struct {
	AuthProviderID uuid.UUID
	Hash           string
}

// UpdatePasswordHash re-hashes at the current cost. A successful sign-in is the
// only moment the plaintext is available to do it with.
func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.AuthProviderID, arg.Hash)
	return err
}

const userProfileByEmail = `-- name: UserProfileByEmail :one
SELECT user_id, email, display_name, timezone, created_at, updated_at FROM user_profiles WHERE email = $1
`

// UserProfileByEmail supports linking a federated identity to an account that
// already exists. Only ever called with an email the provider marked verified —
// matching on an unverified one is an account-takeover route.
func (q *Queries) UserProfileByEmail(ctx context.Context, email string) (UserProfile, error) {
	row := q.db.QueryRow(ctx, userProfileByEmail, email)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
