// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contexts.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createContext = `-- name: CreateContext :one
INSERT INTO contexts (id, user_id, parent_id, slug, name, kind, color, active_hours, tone_profile, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, parent_id, slug, name, kind, color, active_hours, tone_profile, position, is_archived, created_at, updated_at
`

type CreateContextParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ParentID    *uuid.UUID
	Slug        string
	Name        string
	Kind        ContextKind
	Color       *string
	ActiveHours []byte
	ToneProfile *string
	Position    int32
}

// id is supplied by the application as UUIDv7 rather than taken from the
// column default, so rows sort by creation time. See docs/conventions.md §3.
// created_at and updated_at come from defaults and a trigger.
func (q *Queries) CreateContext(ctx context.Context, arg CreateContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, createContext,
		arg.ID,
		arg.UserID,
		arg.ParentID,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.Color,
		arg.ActiveHours,
		arg.ToneProfile,
		arg.Position,
	)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.ActiveHours,
		&i.ToneProfile,
		&i.Position,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContext = `-- name: GetContext :one
SELECT id, user_id, parent_id, slug, name, kind, color, active_hours, tone_profile, position, is_archived, created_at, updated_at FROM contexts WHERE id = $1
`

func (q *Queries) GetContext(ctx context.Context, id uuid.UUID) (Context, error) {
	row := q.db.QueryRow(ctx, getContext, id)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Color,
		&i.ActiveHours,
		&i.ToneProfile,
		&i.Position,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContexts = `-- name: ListContexts :many
SELECT id, user_id, parent_id, slug, name, kind, color, active_hours, tone_profile, position, is_archived, created_at, updated_at
FROM contexts
WHERE user_id = $1
  AND ($2::boolean OR NOT is_archived)
ORDER BY position, name
`

type ListContextsParams struct {
	UserID          uuid.UUID
	IncludeArchived bool
}

func (q *Queries) ListContexts(ctx context.Context, arg ListContextsParams) ([]Context, error) {
	rows, err := q.db.Query(ctx, listContexts, arg.UserID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Context{}
	for rows.Next() {
		var i Context
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.Color,
			&i.ActiveHours,
			&i.ToneProfile,
			&i.Position,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextContextPosition = `-- name: NextContextPosition :one
SELECT COALESCE(MAX(position) + 1, 0)::integer FROM contexts WHERE user_id = $1
`

// NextContextPosition places a new context after the ones that exist.
//
// Read separately rather than computed inside the insert so the insert stays a
// plain statement sqlc can type. A race here costs nothing: two contexts would
// share a position, and ListContexts breaks that tie by name.
func (q *Queries) NextContextPosition(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextContextPosition, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
