// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contexts.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContext = `-- name: CreateContext :one
INSERT INTO contexts (id, user_id, parent_id, name, kind, active_hours, tone_profile, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING id, user_id, parent_id, name, kind, active_hours, tone_profile, is_archived, created_at, updated_at
`

type CreateContextParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ParentID    *uuid.UUID
	Name        string
	Kind        string
	ActiveHours []byte
	ToneProfile string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateContext(ctx context.Context, arg CreateContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, createContext,
		arg.ID,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.Kind,
		arg.ActiveHours,
		arg.ToneProfile,
		arg.CreatedAt,
	)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.ActiveHours,
		&i.ToneProfile,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContext = `-- name: GetContext :one
SELECT id, user_id, parent_id, name, kind, active_hours, tone_profile, is_archived, created_at, updated_at FROM contexts WHERE id = $1
`

func (q *Queries) GetContext(ctx context.Context, id uuid.UUID) (Context, error) {
	row := q.db.QueryRow(ctx, getContext, id)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.ActiveHours,
		&i.ToneProfile,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContexts = `-- name: ListContexts :many
SELECT id, user_id, parent_id, name, kind, active_hours, tone_profile, is_archived, created_at, updated_at
FROM contexts
WHERE user_id = $1
  AND (NOT $2::boolean OR NOT is_archived)
ORDER BY parent_id NULLS FIRST, name
`

type ListContextsParams struct {
	UserID          uuid.UUID
	ExcludeArchived bool
}

func (q *Queries) ListContexts(ctx context.Context, arg ListContextsParams) ([]Context, error) {
	rows, err := q.db.Query(ctx, listContexts, arg.UserID, arg.ExcludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Context{}
	for rows.Next() {
		var i Context
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.ActiveHours,
			&i.ToneProfile,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
