// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignSignalContext(ctx context.Context, arg AssignSignalContextParams) error
	CreateContext(ctx context.Context, arg CreateContextParams) (Context, error)
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetContext(ctx context.Context, id uuid.UUID) (Context, error)
	GetSignalByExternalID(ctx context.Context, arg GetSignalByExternalIDParams) (Signal, error)
	// IngestSignal is idempotent. Re-running a sync over items already seen returns
	// the stored rows untouched rather than writing new ones — signals are
	// immutable, and a database trigger enforces that too.
	IngestSignal(ctx context.Context, arg IngestSignalParams) (Signal, error)
	ListAccountsForContexts(ctx context.Context, contextIds []uuid.UUID) ([]Account, error)
	ListActiveRoutingRules(ctx context.Context, userID uuid.UUID) ([]RoutingRule, error)
	// ListContextTimeline is the read path behind the timeline view. It is
	// context-scoped by construction: there is no unfiltered signal listing.
	ListContextTimeline(ctx context.Context, arg ListContextTimelineParams) ([]ListContextTimelineRow, error)
	ListContexts(ctx context.Context, arg ListContextsParams) ([]Context, error)
	// ListLowConfidenceAssignments backs the manual routing queue. The threshold is
	// open question 1 — the caller supplies it rather than the query assuming one.
	ListLowConfidenceAssignments(ctx context.Context, threshold float64) ([]SignalContext, error)
	// ListUnroutedSignals feeds the router. Oldest first, so a backlog drains in
	// the order things actually happened.
	ListUnroutedSignals(ctx context.Context, arg ListUnroutedSignalsParams) ([]Signal, error)
	// MarkAccountFailed stops the account rather than letting it return partial
	// data: a report must never be silently trusted when a source was down.
	MarkAccountFailed(ctx context.Context, arg MarkAccountFailedParams) error
	// MarkAccountSynced records a successful delta sync.
	MarkAccountSynced(ctx context.Context, arg MarkAccountSyncedParams) error
	// MarkSignalProcessed sets the only column on a signal that may ever change.
	MarkSignalProcessed(ctx context.Context, arg MarkSignalProcessedParams) error
}

var _ Querier = (*Queries)(nil)
