// Package domain holds Warp's entities and the rules that are true of them
// regardless of how they are stored or transported.
//
// Nothing here performs I/O, reads the clock, or imports a framework. The
// router and the extractor are built on this package precisely so they stay
// pure functions of (signal, rules) — which is what makes re-running extraction
// over historical signals possible. See CLAUDE.md, hard invariant 1.
package domain

import (
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// ID is the identifier for every entity. UUIDv7 — time-sortable, generated by
// the application before insert, never by the database.
type ID = uuid.UUID

// NewID returns a fresh UUIDv7.
func NewID() (ID, error) { return uuid.NewV7() }

// MustNewID is for tests and fixtures only.
func MustNewID() ID {
	id, err := uuid.NewV7()
	if err != nil {
		panic(err)
	}
	return id
}

// Clock is passed in wherever the current time is needed. Never call
// time.Now() inside domain logic — a router whose behaviour depends on the wall
// clock cannot be replayed over history.
type Clock func() time.Time

// ErrInvalid is the class of every validation failure in this package.
var ErrInvalid = errors.New("invalid")

func invalidf(format string, args ...any) error {
	return fmt.Errorf("%w: %s", ErrInvalid, fmt.Sprintf(format, args...))
}
